### ISSUE TITLE
_WinHttpSimpleSSLRequest fails on some OS / website combinations

### ISSUE THREAD

**Issue by Danp2** [dragana-r/autoit-winhttp#13]
To reproduce, run example script [_WinHttpSimpleSSLRequest](https://raw.githubusercontent.com/dragana-r/autoit-winhttp/96f4d09cb08b8b672973218a0f482896ef368811/WinHttp_Examples/_WinHttpSimpleSSLRequest.au3) under Window Server 2016.

See https://github.com/Danp2/WebDriver/issues/40 for further details.

**Comment by dragana-r** [comment]
GitHub forces TLS1.2. It appears that WinHTTP doesn't advertise TLS flavor during handshake on such systems when SSL2 is specified even if supported.
That also means that systems with this issue are updated because they shouldn't have TLS1.2 by default.
I've made addition to _WinHttpSimpleSendSSLRequest where this situation is detected and responded to. It should be backward compatible. @Danp2 could you try the code by any chance, if you still have access to such systems?

**Comment by Danp2** [comment]
Appears to work correctly to me. Thanks!
